### ISSUE TITLE
infura id visible on production

### ISSUE THREAD

**Issue by xale76** [ChangoMan/web3modal-example#3]
Hello, great job.
Anyway I see that the infuraId is still visible in production demo. It's a big problem, how to solve this?

**Comment by ChangoMan** [comment]
@xale76 Hello! You would need to use something like environment variables in order to hide the infura ID in production. This differs depending on what company you use for deployment. Vercel, for example, has instructions here: https://vercel.com/docs/projects/environment-variables

**Comment by xale76** [comment]
Thank you for the answer. Anyway, I think that infuraid will be always visibile, because react is a framework that runs on client side. So it needs the value in clear in order to work
